### PR TITLE
Fixes #208 - added onShow and skip methods to SurveyRunItemView

### LINKED ISSUE #208: Subtest-Level Skip Logic not working
On the test assessment Subtest-Level Skip Logic, when you click Yes to answer "End assessment", the app should skip past the next question and take you to the Assessment Complete/Save results screen. In our version, it does not perform this magic.

The code that makes this work is in the second subtest - the one that is skipped - as an Action on display, which is displayCode:

``` javascript
@skip() if ResultOfPrevious("end") is "1"
```

I would have expected that code to be summoned and Coffeescript.exec'd in SurveyRunItemView, but it is not. Check out how similar code - what one would expect - is in QuestionRunItemView

``` javascript
showCode = @model.getString("displayCode")
// snip
CoffeeScript.eval.apply(@, [showCode])
```

The only relevant bit of code in SurveyRunItemView is:

``` javascript
# trigger the question to run it's display code if the subtest's displaycode has already ran
    # if not, add it to a list to run later.
    if @executeReady
      @questionViews[@questionIndex].trigger "show"
    else
      @triggerShowList = [] if not @triggerShowList
      @triggerShowList.push @questionIndex
```

Running this on TC in debug has so far not revealed anything useful. 
http://databases.tangerinecentral.org/group-rti_tanzania_2016_test/_design/ojai/index-dev.html#run/b775d316-e9ec-457a-76c7-869f72ff489b
Looking at the non-marionette versions of these same classes.

### PR DESCRIPTION
**Pull request by chrisekelley**

### CODE REVIEW

File: src/js/modules/subtest/prototypes/SurveyRunItemView.coffee [hunk 1]
```diff
@@ -390,6 +392,34 @@ class SurveyRunItemView extends Backbone.Marionette.CompositeView
 #    #    @trigger "ready"
 #    @trigger "subRendered"
 
+  onShow: ->
```
Comment (rjcorwin) [inline src/js/modules/subtest/prototypes/SurveyRunItemView.coffee:395]: From @chrisekelley : This was added to fix bug #208 and might need to be implemented in other prototypes.
